### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by p0c0p0c0** [p0c0p0c0/Plum#1]
# Server
- [x] Make user authentication
- [ ] Make session and component, data ( **WIP** )
- [ ] Make rest api interface
- [ ] Check validation

# Client
- [ ] Make angular2 base
- [ ] Make login interface
- [ ] Make Session and component, data interface
- [ ] Make administrator panel
